name: release helm chart

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: false
        default: v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: Release ${{ github.event.inputs.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
      - run: ls -a
      - uses: azure/setup-helm@v1
      - run: helm version
      - run: helm package charts/mychart
      - run: ls -a
      - run: mkdir temp/
      - run: mv *.tgz temp/
      - run: helm repo index temp/ --url https://github.com/konveyor/move2kube-operator/releases/download/${{ github.event.inputs.tag }}
      - run: echo 'upload temp/index.yaml'
      - uses: HarikrishnanBalagopal/upload-release-action@v3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
          file: temp/*
          file_glob: true
          overwrite: true
